-- Script de création de la table Player
-- Projet : DGP (Dead God Project)

CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- it_game : Identifiant technique du jeu (obligatoire)
    it_game BIGINT NOT NULL,

    -- name : nom du personnage (obligatoire)
    name VARCHAR(255) NOT NULL,

    -- skin : image.png de l'apparence du personnage
    skin VARCHAR(255) NOT NULL,

    -- stats vie (hp = coeurs rouges, armor = coeurs bleus, black = coeurs noirs)
    hp INTEGER NOT NULL DEFAULT 0,
    armor INTEGER DEFAULT 0,
    black INTEGER DEFAULT 0,

    -- Ressources en jeu
    coins INTEGER DEFAULT 0,
    items INTEGER DEFAULT 0,
    bombs INTEGER DEFAULT 0,
    card INTEGER,
    birthright VARCHAR(255),
    pocket_active INTEGER,

    -- Succès permettant de déploquer le personnage
    achievement INTEGER DEFAULT 0,

    -- Les skins et visuels
    costume INTEGER,
    skin_color INTEGER NOT NULL,
    costume_suffix VARCHAR(255),
    nameimage VARCHAR(255),
    portrait VARCHAR(255),

    -- Contraintes additionnelles pour la sécurité des données
    CONSTRAINT chk_hp_positive CHECK (hp >= 0),
    CONSTRAINT chk_coins_limit CHECK (coins >= 0 AND coins <= 99)
);

-- Commentaires sur la table
COMMENT ON TABLE players IS 'Table stockant les personnages jouables de The Binding of Isaac : Repentance';
COMMENT ON COLUMN players.it_game IS 'Id techniques des personnages après extraction des données de jeu';
COMMENT ON COLUMN players.name IS 'Nom des personnages jouables';
COMMENT ON COLUMN players.skin IS 'Image du skin du personnage à afficher au format png';
COMMENT ON COLUMN players.hp IS 'Nombre de coeurs rouges du personnage au départ';
COMMENT ON COLUMN players.armor IS 'Nombre de coeurs bleus du personnage au départ';
COMMENT ON COLUMN players.black IS 'Nombre de coeurs noirs du personnage au départ';
COMMENT ON COLUMN players.coins IS 'Nombre de pièces du personnage au départ';
COMMENT ON COLUMN players.items IS 'Les items passifs ou actifs du personnage au départ';
COMMENT ON COLUMN players.bombs IS 'Nombre de bombes du personnage au départ';
COMMENT ON COLUMN players.card IS 'Les cartes du personnage au départ';
COMMENT ON COLUMN players.birthright IS 'Indique quel birthright est donné au personnage dans le jeu';
COMMENT ON COLUMN players.pocket_active IS 'Les trinkets du personnage au départ';
COMMENT ON COLUMN players.achievement IS 'it du succès nécessaire pour débloquer le personnage';
COMMENT ON COLUMN players.costume IS 'Image du costume de départ du personnage à afficher au format png';
COMMENT ON COLUMN players.skin_color IS 'Image du costume de départ du personnage à afficher au format png';
COMMENT ON COLUMN players.costume_suffix IS 'Image du costume de départ du personnage à afficher au format png';
COMMENT ON COLUMN players.nameimage IS 'Image du costume de départ du personnage à afficher au format png';
COMMENT ON COLUMN players.portrait IS 'Image du costume de départ du personnage à afficher au format png';
